language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['g++-8', 'g++-8-multilib', 'g++-multilib', 'valgrind', 'expect', 'curl']
      env:
        - COMPILER=g++-8
        - COMP=gcc

    - os: linux
      compiler: clang
      addons:
        apt:
          packages: ['clang-10', 'llvm-10-dev', 'g++-multilib', 'valgrind', 'expect', 'curl']
      env:
        - COMPILER=clang++-10
        - COMP=clang

    - os: osx
      osx_image: xcode12
      compiler: gcc
      env:
        - COMPILER=g++
        - COMP=gcc

    - os: osx
      osx_image: xcode12
      compiler: clang
      env:
        - COMPILER=clang++
        - COMP=clang

branches:
  only:
   - master

before_script:
  - cd src

script:
  # Obtain bench reference from git log
  - git log HEAD | grep "\b[Bb]ench[ :]\+[0-9]\{7\}" | head -n 1 | sed "s/[^0-9]*\([0-9]*\).*/\1/g" > git_sig
  - export benchref=$(cat git_sig)
  - echo "Reference bench:" $benchref
  
  #
  # Compiler version string
  - $COMPILER -v

  #
  # Verify bench number against various builds
  - export CXXFLAGS="-Werror -D_GLIBCXX_DEBUG"
  - make clean && make -j2 ARCH=x86-64 optimize=no debug=yes build && ../tests/signature.sh $benchref
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make clean && make -j2 ARCH=x86-32 optimize=no debug=yes build && ../tests/signature.sh $benchref; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make clean && make -j2 ARCH=x86-32 build && ../tests/signature.sh $benchref; fi

  #
  # Check perft and reproducible search
  - export CXXFLAGS="-Werror"
  - make clean && make -j2 ARCH=x86-64 build
  - ../tests/perft.sh
  - ../tests/reprosearch.sh

  #
  # Valgrind
  #
  - export CXXFLAGS="-O1 -fno-inline"
  - if [ -x "$(command -v valgrind )" ]; then make clean && make -j2 ARCH=x86-64 debug=yes optimize=no build > /dev/null && ../tests/instrumented.sh --valgrind; fi
  - if [ -x "$(command -v valgrind )" ]; then ../tests/instrumented.sh --valgrind-thread; fi

  #
  # Sanitizer
  #
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make clean && make -j2 ARCH=x86-64 sanitize=undefined optimize=no debug=yes build > /dev/null && ../tests/instrumented.sh --sanitizer-undefined; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make clean && make -j2 ARCH=x86-64 sanitize=thread    optimize=no debug=yes build > /dev/null && ../tests/instrumented.sh --sanitizer-thread; fi
