version: 1.0.{build}
clone_depth: 5

branches:
  only:
    - master
    - appveyor

# Operating system (build VM template)
os: Visual Studio 2015

# Build platform, i.e. x86, x64, AnyCPU. This setting is optional.
platform:
  - x86
  - x64
  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

matrix:
  # The build fail immediately once one of the job fails
  fast_finish: true

# Scripts that are called at very beginning, before repo cloning
init:
  - cmake --version
  - msbuild /version

before_build:
  - cd src
  - echo project (DON) >> CMakeLists.txt
  - echo add_executable(DON BitBases.cpp BitBoard.cpp Endgame.cpp Engine.cpp Evaluator.cpp Main.cpp >> CMakeLists.txt
  - echo Material.cpp MoveGenerator.cpp Notation.cpp Pawns.cpp PSQT.cpp Polyglot.cpp Position.cpp Searcher.cpp >> CMakeLists.txt
  - echo TBsyzygy.cpp Thread.cpp Transposition.cpp Option.cpp Zobrist.cpp MemoryHandler.cpp Debugger.cpp >> CMakeLists.txt
  - echo set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/src) >> CMakeLists.txt
#   - echo target_compile_options(DON PUBLIC "/Ox") >> CMakeLists.txt

build_script:
  - cmake -G "Visual Studio 14 2015 Win64" .
  - cmake --build .

before_test:
  - cd Debug
  - DON.exe bench > null
